// die Deutsche Bibliothek — books & dictionary
// All content original. Written in simple German for learners.

const UI_STRINGS = {
  de: {
    home: "Startseite",
    library: "Bibliothek",
    about: "Über",
    progress: "Fortschritt",
    continue: "Weiterlesen",
    startReading: "Lesen beginnen",
    sample: "Leseprobe",
    download: "Herunterladen",
    buy: "Kaufen",
    upload: "Buch hinzufügen",
    chapters: "Kapitel",
    vocabulary: "Wortschatz",
    quiz: "Quiz",
    minutes: "Min.",
    words: "Wörter",
    pages: "Seiten",
    by: "von",
    level: "Niveau",
    allLevels: "Alle Niveaus",
    search: "Suchen…",
    saved: "Gespeichert",
    finished: "Gelesen",
    inProgress: "Begonnen",
    notStarted: "Neu",
    streak: "Tage in Folge",
    learned: "gelernt",
    save: "Speichern",
    known: "Kann ich",
    chapter: "Kapitel",
    of: "von",
    next: "Weiter",
    prev: "Zurück",
    readerPrev: "Zurück",
    readerNext: "Weiter →",
    seeAll: "Alle ansehen",
    featured: "Empfohlen",
    newLevel: "Für diese Stufe",
    yourLibrary: "Deine Bibliothek",
    welcome: "Willkommen zurück",
    yourProgress: "Dein Fortschritt",
    booksFinished: "Bücher fertig",
    wordsLearned: "Wörter gelernt",
    minutesRead: "Minuten gelesen",
    nothingHere: "Noch keine Bücher gefunden.",
    addOwn: "Eigenes Buch hinzufügen",
    addOwnSub: "Lade einen Titel hoch, der in deiner Bibliothek erscheint.",
    title: "Titel",
    description: "Beschreibung",
    content: "Inhalt (eine Zeile pro Absatz)",
    cancel: "Abbrechen",
    add: "Hinzufügen",
    aboutAuthor: "Über den Autor",
    written: "Geschrieben in einfachem Deutsch von Andrew Maier.",
    signIn: "Anmelden",
    signUp: "Registrieren",
    signOut: "Abmelden",
    profile: "Profil",
    donate: "Spenden",
    help: "Hilfe",
    yourAccount: "Dein Konto",
    name: "Name",
    email: "E-Mail",
    password: "Passwort",
    welcomeBack: "Willkommen zurück",
    createAccount: "Konto erstellen",
    noAccount: "Noch kein Konto?",
    haveAccount: "Schon ein Konto?",
    continueAsGuest: "Als Gast weiterlesen",
    editProfile: "Profil bearbeiten",
    save: "Speichern",
    member: "Mitglied seit",
    howTo: "Wie funktioniert es?",
    supportAuthor: "Den Autor unterstützen",
  },
  en: {
    home: "Home",
    library: "Library",
    about: "About",
    progress: "Progress",
    continue: "Continue reading",
    startReading: "Start reading",
    sample: "Sample chapter",
    download: "Download",
    buy: "Buy",
    upload: "Add book",
    chapters: "Chapters",
    vocabulary: "Vocabulary",
    quiz: "Quiz",
    minutes: "min",
    words: "words",
    pages: "pages",
    by: "by",
    level: "Level",
    allLevels: "All levels",
    search: "Search…",
    saved: "Saved",
    finished: "Finished",
    inProgress: "In progress",
    notStarted: "New",
    streak: "day streak",
    learned: "learned",
    save: "Save",
    known: "Know it",
    chapter: "Chapter",
    of: "of",
    next: "Next",
    prev: "Previous",
    readerPrev: "← Previous",
    readerNext: "Next →",
    seeAll: "See all",
    featured: "Featured",
    newLevel: "For your level",
    yourLibrary: "Your library",
    welcome: "Welcome back",
    yourProgress: "Your progress",
    booksFinished: "Books finished",
    wordsLearned: "Words learned",
    minutesRead: "Minutes read",
    nothingHere: "No books found.",
    addOwn: "Add your own book",
    addOwnSub: "Upload a title and it will appear in your library.",
    title: "Title",
    description: "Description",
    content: "Content (one paragraph per line)",
    cancel: "Cancel",
    add: "Add",
    aboutAuthor: "About the author",
    written: "Written in simple German by Andrew Maier.",
    signIn: "Sign in",
    signUp: "Sign up",
    signOut: "Sign out",
    profile: "Profile",
    donate: "Donate",
    help: "Help",
    yourAccount: "Your account",
    name: "Name",
    email: "Email",
    password: "Password",
    welcomeBack: "Welcome back",
    createAccount: "Create account",
    noAccount: "No account yet?",
    haveAccount: "Already have an account?",
    continueAsGuest: "Continue as guest",
    editProfile: "Edit profile",
    save: "Save",
    member: "Member since",
    howTo: "How it works",
    supportAuthor: "Support the author",
  },
  ru: {
    home: "Главная",
    library: "Библиотека",
    about: "Об авторе",
    progress: "Прогресс",
    continue: "Продолжить",
    startReading: "Начать читать",
    sample: "Образец",
    download: "Скачать",
    buy: "Купить",
    upload: "Добавить книгу",
    chapters: "Главы",
    vocabulary: "Словарь",
    quiz: "Тест",
    minutes: "мин",
    words: "слов",
    pages: "стр.",
    by: "автор",
    level: "Уровень",
    allLevels: "Все уровни",
    search: "Поиск…",
    saved: "Сохранено",
    finished: "Прочитано",
    inProgress: "В процессе",
    notStarted: "Новое",
    streak: "дней подряд",
    learned: "выучено",
    save: "Сохранить",
    known: "Знаю",
    chapter: "Глава",
    of: "из",
    next: "Дальше",
    prev: "Назад",
    readerPrev: "← Назад",
    readerNext: "Дальше →",
    seeAll: "Все",
    featured: "Рекомендуемое",
    newLevel: "Для твоего уровня",
    yourLibrary: "Твоя библиотека",
    welcome: "С возвращением",
    yourProgress: "Твой прогресс",
    booksFinished: "Книг прочитано",
    wordsLearned: "Слов выучено",
    minutesRead: "Минут чтения",
    nothingHere: "Книг не найдено.",
    addOwn: "Добавить свою книгу",
    addOwnSub: "Загрузи название — оно появится в библиотеке.",
    title: "Название",
    description: "Описание",
    content: "Текст (по абзацу на строку)",
    cancel: "Отмена",
    add: "Добавить",
    aboutAuthor: "Об авторе",
    written: "Написано на простом немецком языке Эндрю Майером.",
    signIn: "Войти",
    signUp: "Регистрация",
    signOut: "Выйти",
    profile: "Профиль",
    donate: "Поддержать",
    help: "Помощь",
    yourAccount: "Твой аккаунт",
    name: "Имя",
    email: "Эл. почта",
    password: "Пароль",
    welcomeBack: "С возвращением",
    createAccount: "Создать аккаунт",
    noAccount: "Нет аккаунта?",
    haveAccount: "Уже есть аккаунт?",
    continueAsGuest: "Продолжить как гость",
    editProfile: "Изменить профиль",
    save: "Сохранить",
    member: "Участник с",
    howTo: "Как это работает",
    supportAuthor: "Поддержать автора",
  },
};

// Mini dictionary: German → { pos, en, ru, lemma? }
const DICT = {
  // articles & basic
  "der": { pos: "art", en: "the (m.)", ru: "the (м.р.)" },
  "die": { pos: "art", en: "the (f./pl.)", ru: "the (ж.р./мн.ч.)" },
  "das": { pos: "art", en: "the (n.)", ru: "the (ср.р.)" },
  "ein": { pos: "art", en: "a / an", ru: "один, какой-то" },
  "eine": { pos: "art", en: "a / an", ru: "одна, какая-то" },
  "einen": { pos: "art", en: "a / an (acc.)", ru: "одного (вин.)" },
  "und": { pos: "conj", en: "and", ru: "и" },
  "oder": { pos: "conj", en: "or", ru: "или" },
  "aber": { pos: "conj", en: "but", ru: "но" },
  "weil": { pos: "conj", en: "because", ru: "потому что" },
  "wenn": { pos: "conj", en: "when / if", ru: "когда / если" },
  "dass": { pos: "conj", en: "that", ru: "что" },
  // pronouns
  "ich": { pos: "pron", en: "I", ru: "я" },
  "du": { pos: "pron", en: "you (informal)", ru: "ты" },
  "er": { pos: "pron", en: "he", ru: "он" },
  "sie": { pos: "pron", en: "she / they", ru: "она / они" },
  "es": { pos: "pron", en: "it", ru: "оно" },
  "wir": { pos: "pron", en: "we", ru: "мы" },
  "ihr": { pos: "pron", en: "you (pl.) / her", ru: "вы / её" },
  "mein": { pos: "pron", en: "my", ru: "мой" },
  "meine": { pos: "pron", en: "my (f./pl.)", ru: "моя" },
  "sein": { pos: "verb", en: "to be / his", ru: "быть / его" },
  // verbs (common)
  "ist": { pos: "verb", en: "is", ru: "есть, является", lemma: "sein" },
  "sind": { pos: "verb", en: "are", ru: "есть (мн.ч.)", lemma: "sein" },
  "war": { pos: "verb", en: "was", ru: "был", lemma: "sein" },
  "waren": { pos: "verb", en: "were", ru: "были", lemma: "sein" },
  "hat": { pos: "verb", en: "has", ru: "имеет", lemma: "haben" },
  "habe": { pos: "verb", en: "(I) have", ru: "(я) имею", lemma: "haben" },
  "hatte": { pos: "verb", en: "had", ru: "имел", lemma: "haben" },
  "geht": { pos: "verb", en: "goes", ru: "идёт", lemma: "gehen" },
  "ging": { pos: "verb", en: "went", ru: "шёл", lemma: "gehen" },
  "kommt": { pos: "verb", en: "comes", ru: "приходит", lemma: "kommen" },
  "kam": { pos: "verb", en: "came", ru: "пришёл", lemma: "kommen" },
  "sieht": { pos: "verb", en: "sees", ru: "видит", lemma: "sehen" },
  "sah": { pos: "verb", en: "saw", ru: "увидел", lemma: "sehen" },
  "sagt": { pos: "verb", en: "says", ru: "говорит", lemma: "sagen" },
  "sagte": { pos: "verb", en: "said", ru: "сказал", lemma: "sagen" },
  "macht": { pos: "verb", en: "makes / does", ru: "делает", lemma: "machen" },
  "machte": { pos: "verb", en: "made / did", ru: "сделал", lemma: "machen" },
  "denkt": { pos: "verb", en: "thinks", ru: "думает", lemma: "denken" },
  "dachte": { pos: "verb", en: "thought", ru: "думал", lemma: "denken" },
  "weiß": { pos: "verb", en: "knows", ru: "знает", lemma: "wissen" },
  "kennt": { pos: "verb", en: "knows (person)", ru: "знает (кого)", lemma: "kennen" },
  "möchte": { pos: "verb", en: "would like", ru: "хотел бы", lemma: "mögen" },
  "will": { pos: "verb", en: "wants", ru: "хочет", lemma: "wollen" },
  "kann": { pos: "verb", en: "can", ru: "может", lemma: "können" },
  "muss": { pos: "verb", en: "must", ru: "должен", lemma: "müssen" },
  "soll": { pos: "verb", en: "should", ru: "должен", lemma: "sollen" },
  "wohnt": { pos: "verb", en: "lives", ru: "живёт", lemma: "wohnen" },
  "arbeitet": { pos: "verb", en: "works", ru: "работает", lemma: "arbeiten" },
  "trinkt": { pos: "verb", en: "drinks", ru: "пьёт", lemma: "trinken" },
  "isst": { pos: "verb", en: "eats", ru: "ест", lemma: "essen" },
  "liest": { pos: "verb", en: "reads", ru: "читает", lemma: "lesen" },
  "schreibt": { pos: "verb", en: "writes", ru: "пишет", lemma: "schreiben" },
  "fährt": { pos: "verb", en: "drives / travels", ru: "едет", lemma: "fahren" },
  "öffnet": { pos: "verb", en: "opens", ru: "открывает", lemma: "öffnen" },
  "schließt": { pos: "verb", en: "closes", ru: "закрывает", lemma: "schließen" },
  "findet": { pos: "verb", en: "finds", ru: "находит", lemma: "finden" },
  "fand": { pos: "verb", en: "found", ru: "нашёл", lemma: "finden" },
  "sucht": { pos: "verb", en: "looks for", ru: "ищет", lemma: "suchen" },
  "bleibt": { pos: "verb", en: "stays", ru: "остаётся", lemma: "bleiben" },
  "lacht": { pos: "verb", en: "laughs", ru: "смеётся", lemma: "lachen" },
  "lächelt": { pos: "verb", en: "smiles", ru: "улыбается", lemma: "lächeln" },
  "schläft": { pos: "verb", en: "sleeps", ru: "спит", lemma: "schlafen" },
  "wartet": { pos: "verb", en: "waits", ru: "ждёт", lemma: "warten" },
  "fragt": { pos: "verb", en: "asks", ru: "спрашивает", lemma: "fragen" },
  "antwortet": { pos: "verb", en: "answers", ru: "отвечает", lemma: "antworten" },
  // nouns
  "Tag": { pos: "noun", en: "day", ru: "день" },
  "Nacht": { pos: "noun", en: "night", ru: "ночь" },
  "Morgen": { pos: "noun", en: "morning", ru: "утро" },
  "Abend": { pos: "noun", en: "evening", ru: "вечер" },
  "Park": { pos: "noun", en: "park", ru: "парк" },
  "Stadt": { pos: "noun", en: "city", ru: "город" },
  "Dorf": { pos: "noun", en: "village", ru: "деревня" },
  "Haus": { pos: "noun", en: "house", ru: "дом" },
  "Frau": { pos: "noun", en: "woman / Mrs.", ru: "женщина / госпожа" },
  "Mann": { pos: "noun", en: "man", ru: "мужчина" },
  "Kind": { pos: "noun", en: "child", ru: "ребёнок" },
  "Junge": { pos: "noun", en: "boy", ru: "мальчик" },
  "Mädchen": { pos: "noun", en: "girl", ru: "девочка" },
  "Hund": { pos: "noun", en: "dog", ru: "собака" },
  "Katze": { pos: "noun", en: "cat", ru: "кошка" },
  "Vogel": { pos: "noun", en: "bird", ru: "птица" },
  "Baum": { pos: "noun", en: "tree", ru: "дерево" },
  "Bank": { pos: "noun", en: "bench / bank", ru: "скамейка / банк" },
  "Buch": { pos: "noun", en: "book", ru: "книга" },
  "Brief": { pos: "noun", en: "letter", ru: "письмо" },
  "Bäcker": { pos: "noun", en: "baker", ru: "пекарь" },
  "Brot": { pos: "noun", en: "bread", ru: "хлеб" },
  "Brötchen": { pos: "noun", en: "bread roll", ru: "булочка" },
  "Kaffee": { pos: "noun", en: "coffee", ru: "кофе" },
  "Wasser": { pos: "noun", en: "water", ru: "вода" },
  "Wald": { pos: "noun", en: "forest", ru: "лес" },
  "Schlüssel": { pos: "noun", en: "key", ru: "ключ" },
  "Tür": { pos: "noun", en: "door", ru: "дверь" },
  "Fenster": { pos: "noun", en: "window", ru: "окно" },
  "Straße": { pos: "noun", en: "street", ru: "улица" },
  "Zug": { pos: "noun", en: "train", ru: "поезд" },
  "Bahnhof": { pos: "noun", en: "train station", ru: "вокзал" },
  "Reise": { pos: "noun", en: "journey", ru: "путешествие" },
  "Auto": { pos: "noun", en: "car", ru: "машина" },
  "Hand": { pos: "noun", en: "hand", ru: "рука" },
  "Augen": { pos: "noun", en: "eyes", ru: "глаза" },
  "Stimme": { pos: "noun", en: "voice", ru: "голос" },
  "Name": { pos: "noun", en: "name", ru: "имя" },
  "Anna": { pos: "noun", en: "Anna (name)", ru: "Анна" },
  "Paul": { pos: "noun", en: "Paul (name)", ru: "Пауль" },
  "Berlin": { pos: "noun", en: "Berlin", ru: "Берлин" },
  "München": { pos: "noun", en: "Munich", ru: "Мюнхен" },
  "Schwarzwald": { pos: "noun", en: "Black Forest", ru: "Шварцвальд" },
  // adjectives & adverbs
  "klein": { pos: "adj", en: "small", ru: "маленький" },
  "groß": { pos: "adj", en: "big", ru: "большой" },
  "neu": { pos: "adj", en: "new", ru: "новый" },
  "alt": { pos: "adj", en: "old", ru: "старый" },
  "schön": { pos: "adj", en: "beautiful", ru: "красивый" },
  "warm": { pos: "adj", en: "warm", ru: "тёплый" },
  "kalt": { pos: "adj", en: "cold", ru: "холодный" },
  "gut": { pos: "adj", en: "good", ru: "хороший" },
  "schlecht": { pos: "adj", en: "bad", ru: "плохой" },
  "schnell": { pos: "adj", en: "fast", ru: "быстрый" },
  "langsam": { pos: "adj", en: "slow", ru: "медленный" },
  "müde": { pos: "adj", en: "tired", ru: "уставший" },
  "froh": { pos: "adj", en: "happy / glad", ru: "радостный" },
  "still": { pos: "adj", en: "quiet", ru: "тихий" },
  "leise": { pos: "adj", en: "quiet (sound)", ru: "тихо" },
  "laut": { pos: "adj", en: "loud", ru: "громко" },
  "dunkel": { pos: "adj", en: "dark", ru: "тёмный" },
  "hell": { pos: "adj", en: "bright", ru: "светлый" },
  "ruhig": { pos: "adj", en: "calm", ru: "спокойный" },
  "fremd": { pos: "adj", en: "strange / foreign", ru: "чужой" },
  "verloren": { pos: "adj", en: "lost", ru: "потерянный" },
  // prepositions
  "in": { pos: "prep", en: "in / into", ru: "в" },
  "im": { pos: "prep", en: "in the (m./n.)", ru: "в (м./ср.)" },
  "auf": { pos: "prep", en: "on / onto", ru: "на" },
  "an": { pos: "prep", en: "at / on", ru: "у / на" },
  "am": { pos: "prep", en: "at the / on the", ru: "у / на" },
  "mit": { pos: "prep", en: "with", ru: "с" },
  "von": { pos: "prep", en: "from / of", ru: "от / из" },
  "vom": { pos: "prep", en: "from the", ru: "от" },
  "zu": { pos: "prep", en: "to", ru: "к" },
  "nach": { pos: "prep", en: "to / after", ru: "после / в" },
  "für": { pos: "prep", en: "for", ru: "для" },
  "ohne": { pos: "prep", en: "without", ru: "без" },
  "über": { pos: "prep", en: "over / about", ru: "над / о" },
  "durch": { pos: "prep", en: "through", ru: "через" },
  // misc
  "nicht": { pos: "adv", en: "not", ru: "не" },
  "auch": { pos: "adv", en: "also", ru: "тоже" },
  "nur": { pos: "adv", en: "only", ru: "только" },
  "sehr": { pos: "adv", en: "very", ru: "очень" },
  "heute": { pos: "adv", en: "today", ru: "сегодня" },
  "gestern": { pos: "adv", en: "yesterday", ru: "вчера" },
  "morgen": { pos: "adv", en: "tomorrow", ru: "завтра" },
  "hier": { pos: "adv", en: "here", ru: "здесь" },
  "da": { pos: "adv", en: "there", ru: "там" },
  "dort": { pos: "adv", en: "over there", ru: "там" },
  "dann": { pos: "adv", en: "then", ru: "потом" },
  "jetzt": { pos: "adv", en: "now", ru: "сейчас" },
  "schon": { pos: "adv", en: "already", ru: "уже" },
  "noch": { pos: "adv", en: "still / yet", ru: "ещё" },
  "ja": { pos: "part", en: "yes", ru: "да" },
  "nein": { pos: "part", en: "no", ru: "нет" },
  "Hallo": { pos: "intj", en: "hello", ru: "привет" },
  "Guten": { pos: "adj", en: "good (acc.)", ru: "доброго", lemma: "gut" },
  // Additional declined / plural forms — show lemma
  "Bücher": { pos: "noun", en: "books (pl.)", ru: "книги", lemma: "Buch" },
  "Männer": { pos: "noun", en: "men (pl.)", ru: "мужчины", lemma: "Mann" },
  "Frauen": { pos: "noun", en: "women (pl.)", ru: "женщины", lemma: "Frau" },
  "Kinder": { pos: "noun", en: "children", ru: "дети", lemma: "Kind" },
  "Häuser": { pos: "noun", en: "houses", ru: "дома", lemma: "Haus" },
  "Augen": { pos: "noun", en: "eyes", ru: "глаза", lemma: "Auge" },
  "Wälder": { pos: "noun", en: "forests", ru: "леса", lemma: "Wald" },
  "Bäume": { pos: "noun", en: "trees", ru: "деревья", lemma: "Baum" },
  "Vögel": { pos: "noun", en: "birds", ru: "птицы", lemma: "Vogel" },
  "Türen": { pos: "noun", en: "doors", ru: "двери", lemma: "Tür" },
  "Stimmen": { pos: "noun", en: "voices", ru: "голоса", lemma: "Stimme" },
  "Tage": { pos: "noun", en: "days", ru: "дни", lemma: "Tag" },
  "Hunde": { pos: "noun", en: "dogs", ru: "собаки", lemma: "Hund" },
  "Dörfer": { pos: "noun", en: "villages", ru: "деревни", lemma: "Dorf" },
  "Brötchen": { pos: "noun", en: "bread rolls", ru: "булочки", lemma: "Brötchen" },
  "kleinen": { pos: "adj", en: "small (decl.)", ru: "маленького", lemma: "klein" },
  "kleiner": { pos: "adj", en: "small (decl.)", ru: "маленький", lemma: "klein" },
  "schönen": { pos: "adj", en: "beautiful (decl.)", ru: "красивого", lemma: "schön" },
  "alten": { pos: "adj", en: "old (decl.)", ru: "старого", lemma: "alt" },
  "großen": { pos: "adj", en: "big (decl.)", ru: "большого", lemma: "groß" },
  "gutes": { pos: "adj", en: "good (n.)", ru: "хорошее", lemma: "gut" },
  "guten": { pos: "adj", en: "good (decl.)", ru: "хорошего", lemma: "gut" },
  "neuen": { pos: "adj", en: "new (decl.)", ru: "нового", lemma: "neu" },
  "dem": { pos: "art", en: "the (dat. m./n.)", ru: "the (дат. м./ср.)", lemma: "der" },
  "den": { pos: "art", en: "the (acc. m. / dat. pl.)", ru: "the (вин. м.)", lemma: "der" },
  "des": { pos: "art", en: "the (gen. m./n.)", ru: "the (род. м./ср.)", lemma: "der" },
  "ihn": { pos: "pron", en: "him", ru: "его", lemma: "er" },
  "ihm": { pos: "pron", en: "(to) him", ru: "ему", lemma: "er" },
  "ihr": { pos: "pron", en: "you (pl.) / her (dat.)", ru: "вы / ей", lemma: "sie" },
  "mich": { pos: "pron", en: "me (acc.)", ru: "меня", lemma: "ich" },
  "mir": { pos: "pron", en: "(to) me", ru: "мне", lemma: "ich" },
  "dich": { pos: "pron", en: "you (acc.)", ru: "тебя", lemma: "du" },
  "dir": { pos: "pron", en: "(to) you", ru: "тебе", lemma: "du" },
  "gegangen": { pos: "verb", en: "gone", ru: "ушёл", lemma: "gehen" },
  "gekommen": { pos: "verb", en: "come", ru: "пришёл", lemma: "kommen" },
  "gesehen": { pos: "verb", en: "seen", ru: "увиденный", lemma: "sehen" },
  "gegessen": { pos: "verb", en: "eaten", ru: "съеденный", lemma: "essen" },
  "gelesen": { pos: "verb", en: "read (pp.)", ru: "прочитанный", lemma: "lesen" },
  "geschrieben": { pos: "verb", en: "written", ru: "написанный", lemma: "schreiben" },
  "gefunden": { pos: "verb", en: "found", ru: "найденный", lemma: "finden" },
  "gesagt": { pos: "verb", en: "said", ru: "сказанный", lemma: "sagen" },
  "gemacht": { pos: "verb", en: "done / made", ru: "сделанный", lemma: "machen" },
  "gewesen": { pos: "verb", en: "been", ru: "был", lemma: "sein" },
  "gehabt": { pos: "verb", en: "had", ru: "имел", lemma: "haben" },
};

const lookupWord = (raw) => {
  if (!raw) return null;
  const clean = raw.replace(/[.,;:!?"„"()«»…\-]/g, "").trim();
  if (!clean) return null;
  if (DICT[clean]) return { word: clean, ...DICT[clean] };
  const lower = clean.toLowerCase();
  if (DICT[lower]) return { word: lower, ...DICT[lower] };
  // try uppercased noun form
  const cap = lower.charAt(0).toUpperCase() + lower.slice(1);
  if (DICT[cap]) return { word: cap, ...DICT[cap] };
  // fall back to the per-book glossary loaded at runtime (DICT keeps precedence)
  const G = (typeof window !== 'undefined' && window.GLOSSARY) ? window.GLOSSARY : {};
  if (G[clean]) return { word: clean, ...G[clean] };
  if (G[lower]) return { word: lower, ...G[lower] };
  if (G[cap]) return { word: cap, ...G[cap] };
  return { word: clean, pos: "—", en: "—", ru: "—", unknown: true };
};

// ---------- BOOKS ----------
// Catalog is loaded at runtime from books/manifest.json (see loader.js).
const BOOKS = [];

// Build a vocab record per book with translations from DICT
const buildVocab = (book) => {
  return (book.vocab || []).map(w => {
    const entry = DICT[w] || DICT[w.toLowerCase()] || DICT[w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()] || { pos: "—", en: "—", ru: "—" };
    return { word: w, ...entry };
  });
};

// Quiz: generated from chapter text
const makeQuiz = (book) => {
  const qs = [];
  const chapters = book.chapters;
  // Q1: who/what is the protagonist
  const protag = book.title.match(/Anna/) ? "Anna" : book.title.match(/Paul/) ? "Paul" : book.title.match(/Maria/) ? "Maria" : book.title.match(/Lukas/) ? "Lukas" : book.title.match(/Markus/) ? "Markus" : "Anna";
  qs.push({
    prompt: { de: `Wer ist die Hauptfigur in „${book.title}"?`, en: `Who is the main character in "${book.title}"?`, ru: `Кто главный герой в «${book.title}»?` },
    options: [protag, "Hans", "Karl", "Lisa"].sort(() => Math.random() - 0.5),
    answer: protag,
  });
  qs.push({
    prompt: { de: `Was bedeutet „Tag"?`, en: `What does „Tag" mean?`, ru: `Что значит „Tag"?` },
    options: ["night", "day", "tree", "house"],
    answer: "day",
  });
  qs.push({
    prompt: { de: "Wo spielt die erste Szene?", en: "Where does the first scene take place?", ru: "Где происходит первая сцена?" },
    options: [chapters[0].title, "Im Schloss", "Auf dem Schiff", "Auf dem Mond"],
    answer: chapters[0].title,
  });
  return qs;
};

window.UI_STRINGS = UI_STRINGS;
window.DICT = DICT;
function fmtReadingTime(m, minUnit) {
  if (m < 60) return m + " " + minUnit;
  const h = Math.floor(m / 60), mm = m % 60;
  return mm ? (h + " h " + mm + " " + minUnit) : (h + " h");
}
window.fmtReadingTime = fmtReadingTime;
window.lookupWord = lookupWord;
window.BOOKS = BOOKS;
window.buildVocab = buildVocab;
window.makeQuiz = makeQuiz;
